### ISSUE TITLE
No permission to download the pretrained model.

### ISSUE THREAD

**Issue by Barnonewdm** [rhgao/Im2Flow#1]
bash model/download_model.sh Im2Flow
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2018-06-19 15:16:19--  http://vision.cs.utexas.edu/projects/im2flow/models/Im2Flow.t7
Resolving vision.cs.utexas.edu (vision.cs.utexas.edu)... 128.83.120.116
Connecting to vision.cs.utexas.edu (vision.cs.utexas.edu)|128.83.120.116|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-06-19 15:16:20 ERROR 403: Forbidden.

**Comment by rhgao** [comment]
It should be fixed now. Thanks!
