### ISSUE TITLE
flow visualization and flow magnitude 

### ISSUE THREAD

**Issue by bragilee** [rhgao/Im2Flow#2]
Hi,

Thank you for your code.
I have one question in line 49 in visualizeFlow.py.
        predicted_mgt = predicted_flow[:,:,2] / 255.0 * 30
What does 30 mean?
Actually I am a bit confused how do you normalize the magnitude value to range [-1, 1] as the input to the network?

Very appreciate your time and efforts.

**Comment by rhgao** [comment]
Hi,

30 is the maximum of the flow magnitude used when computing the flow image.

The magnitude value is clipped to the range [0,30] and then directly mapped to [-1,1].

Hope this answers your question.

**Comment by bragilee** [comment]
Thank your so much for your explanation!
